### ISSUE TITLE
Editing task should update the task ID

### ISSUE THREAD

**Issue by xhh** [sjl/t#1]
E.g. At first I have a task "abc":
t abc
(abc | id:a9993e364706816aba3e25717850c26c9cd0d89d)

Then I change it to "cde":
t -e a cde
(cde | id:a9993e364706816aba3e25717850c26c9cd0d89d)

Then assume I find "abc" should be a separate task, so I add the task again:
t abc
(abc | id:a9993e364706816aba3e25717850c26c9cd0d89d)

But, the updated task "cde" is missing (overridden by the new added task).

I suggest the ID is also re-generated when editing tasks.

**Comment by dkasak** [comment]
@sjl, this should be closed now.

**Comment by sjl** [comment]
dammit github
