### ISSUE TITLE
task id's being generated randomly and are changing

### ISSUE THREAD

**Issue by omm9** [sjl/t#24]
Tasks desc below represents the task order in which they are added. You can see the task id generated here being either alpha or numeric without any order
$ t
5 - third_task
6 - 4th_task
a - first task
e - sec task
f - fifth task

Next, when 6th task is added, 4th task id is changed.
$ t 6th_task
$ t
5  - third_task
69 - 6th_task
6b - 4th_task
a  - first task
e  - sec task
f  - fifth task

Thanks,
Om

**Comment by sjl** [comment]
> You can see the task id generated here being either alpha or numeric without any order

This is described in the README: https://github.com/sjl/t/#it-plays-nice-with-version-control

> Next, when 6th task is added, 4th task id is changed.

`t` only shows you as much of the task ID as is required to uniquely identify it.  Before you added the `6th_task`, the prefix `6` was enough to uniquely identify that task.  After you added that new task, the ID prefix `6` is no longer enough, and now you need another character.

You can see the full task IDs with `t --verbose`:

```
sjl at alephnull in ~/plan on master? 
><((°> t --verbose 
5d9079ff78ec7ab15d883036c8dd9b27353735e1 - third_task 
69025365f9b88e2124b1dbc807805b5a84d698de - 6th_task 
6b3d89f7b4e7df0fdbf8041d182bb332eeb4d3a9 - 4th_task 
a807e6d661031161427fa3c6f3e6a586ac15242a - first task 
e76f6d5485758ae775b1162d259c9e01a954bdbe - sec task 
fcc118abecc404580b82d3f787de69da97b078f7 - fifth task 
```
