### ISSUE TITLE
Breaking t with apostrophes

### ISSUE THREAD

**Issue by dmoa** [sjl/t#26]
![image](https://user-images.githubusercontent.com/44374106/79032497-eed1d680-7b9e-11ea-9a4b-d87390511497.png)

When writing a single apostrophe, the program seems to fall into full chaos mode.
I have tried no variants as I did not want to clog up my list of tasks with junk errors.

Thoughts?

**Comment by Gerschel** [comment]
From my experience, I was able to use quotes to input text that would otherwise be commands. Escape it.  

rewrite of spruce with  j\'s  ...

**Comment by dmoa** [comment]
Works for me!
I don't think it's worth closing the issue however as that seems like a useful but annoying fix.

**Comment by sjl** [comment]
The quotes are getting handled by your shell before t is ever run.  The same thing would happen with any program you ran:

```
sjl at ouroboros in ~ $ echo foo's test 
> 
> 
> xyz' 
foos test 
 
 
xyz 
```

I'll add a check to `t` to fail if newlines are present in the task text, because that messes with the file format.
