### ISSUE TITLE
Integration with fzf or similar 

### ISSUE THREAD

**Issue by sardaukar** [sjl/t#28]
Thanks for the project, seems interesting. Is it possible to use fzf or any other file finder to select between list files in a folder for example? Thanks again

**Comment by doczi-dominik** [comment]
You can specify the tasklist to use using `--list / -l` and the working directory using `--task-dir / -t`, so a simple shellscript like this could work:

```sh
#!/bin/sh
TASK_DIR="$HOME/tasklists"
TASKFILE=$(find "$TASK_DIR" -maxdepth 1 -type f -printf "%f\n" | fzf)
t --task-dir="$TASK_DIR" --list="$TASKFILE" "$@"
```

**Comment by sardaukar** [comment]
Thanks!
